FROM node:18

ARG NEXT_PUBLIC_DATADOG_APP_ID
ARG NEXT_PUBLIC_DATADOG_CLIENT_TOKEN

ENV NEXT_PUBLIC_DATADOG_APP_ID=$NEXT_PUBLIC_DATADOG_APP_ID
ENV NEXT_PUBLIC_DATADOG_CLIENT_TOKEN=$NEXT_PUBLIC_DATADOG_CLIENT_TOKEN

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]