name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: 1rodrigoassis/portfolio
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: SSH into EC2 and redeploy
      #   uses: appleboy/ssh-action@v0.1.8
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ec2-user
      #     key: ${{ secrets.EC2_KEY }}
      #     script: |
      #       docker pull user/my-app:latest
      #       docker stop my-app || true
      #       docker rm my-app || true
      #       docker run -d --name my-app -p 80:3000 user/my-app:latest
