name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GIT_COMMIT_HASH: ${{ github.sha | cut -c1-7 }}
      NEXT_PUBLIC_DATADOG_APP_ID: ${{ secrets.NEXT_PUBLIC_DATADOG_APP_ID }}
      NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: ${{ secrets.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN }}
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOST_IP: ${{ secrets.SSH_HOST_IP }}
      USER_NAME: ${{ secrets.USER_NAME }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Push Docker image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: 1rodrigoassis/portfolio
          registry: docker.io
          dockerfile: Dockerfile
          buildContext: . 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ env.GIT_COMMIT_HASH }}
          buildArgs: NEXT_PUBLIC_DATADOG_APP_ID=${{ env.NEXT_PUBLIC_DATADOG_APP_ID }},NEXT_PUBLIC_DATADOG_CLIENT_TOKEN=${{ env.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN }}

      - name: Deploy to EC2
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_IP} '
            docker pull 1rodrigoassis/portfolio:${{ env.GIT_COMMIT_HASH }}
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --restart unless-stopped --name portfolio -p 3000:3000 1rodrigoassis/portfolio:${{ env.GIT_COMMIT_HASH }}
          '
